### PR TITLE
Check done intermediary models only when tuple is Done

### PR DESCRIPTION
**Pull request by inelgnu**
This will perform a check of done intermediary models only when a tuple is Done, to avoid MVCC.

This PR is targeting master, the commit is already present is melloddy branch and the tag 0.0.9-melloddy.1

### CODE REVIEW

**Review by thibaultrobert — DISMISSED** [review]
Becarefull the size of the event that this update generate will grow with the size of the compute plan and may exceed GRPC size limit.

**Comment by inelgnu** [comment]
@thibaultrobert I don't understand your point here, why would this impact the new behavior and not the previous one?

**Comment by thibaultrobert** [comment]
https://github.com/SubstraFoundation/substra-chaincode/pull/123#issuecomment-665272500
It won't you're right. I've completely misunderstood your commit here. Sorry about that and once again the noise.

**Comment by AurelienGasser** [comment]
End to end tests: :heavy_check_mark:

**Review by AurelienGasser — APPROVED** [review]

**Pull request merged**
