### PR TITLE
Fix gocritic warnings

### PR DESCRIPTION
**Pull request by olivierperes**
These warnings were reported by [go-critic](https://github.com/go-critic/go-critic).

### CODE REVIEW

**Comment by Kelvin-M** [comment]
@olivierperes Can you rebase on `dev` to be able to do the review ?

**Comment by olivierperes** [comment]
@Kelvin-M Rebased.

**Comment by Kelvin-M** [comment]
Nice work, using switch case improve the reading of the code, thank you ! 
I let the code owners (@inalgnu @thibaultrobert ) do the review :)

**Review by thibaultrobert — APPROVED** [review]
It's not a habit of mine but it's indeed good practice. Thank you.

**Pull request merged**
