### PR TITLE
travis: optimize lint

### PR DESCRIPTION
**Pull request by AurelienGasser**
**1. Lint only our modules:**

- Running `golint` doesn't lint the `errors/` package.
- Running `golint ./...` lints the `vendors/` package, which is wrong too.
- => Use `go list` with a grep in order to lint only the packages we wrote

**2. Try building the chaincode even if linting fails**

Rationale: I assume it's always interesting to see if the package can build, even if linting failed.

### CODE REVIEW

**Comment by AurelienGasser** [comment]
Running `golint` _after_ `go build` leads to the error

```
chaincode:1:1: illegal character U+007F
```

I'll try a new approach: lint before the build, but try building even if linting fails.

**Comment by AurelienGasser** [comment]
Looks like it works:

- It caught the error in the main directory
- It caught the error in the `errors/` subdirectory
- It still tried to `go build` the package
- The CI build gets marked as "failed" out because of the lint errors

I'll remove the intentional lint errors.

**Comment by AurelienGasser** [comment]
This is ready for review. 

Sorry for the noise !

**Comment by AurelienGasser** [comment]
Today I learned: adding `: ` (colon followed by a space) to a travis command makes the YAML invalid! Because `: ` is part of the YAML syntax.

**Review by thibaultrobert — APPROVED** [review]

**Pull request merged**
