### PR TITLE
fix issue #65

### PR DESCRIPTION
**Pull request by inelgnu**

### CODE REVIEW

**Comment by samlesu** [comment]
Well done the investigation and the work @thibaultrobert and @inalgnu. 

As far as I understand, these changes are solving two issues:
1. a recursion issue when creating tuple (bug #65)
2. timeout error on asset creation (linked to https://github.com/SubstraFoundation/substra-backend/issues/10)

Do you think it would be worth splitting this PR into two separate PRs? It could then be easier to track the changes and could also speed up the review/merge process faster.

**Comment by samlesu** [comment]
I'm wondering the side effect of removing the conflict error when  creating a compute plan / traintuple.

- Would it be possible to create a compute plan depending on existing traintuples (= on existing compute plans)?
- If yes, we may have to handle a few corner cases:
  - compute plan depending on other compute plan: cleanup in the backend?
  - handle 'failed', 'canceled' statuses

**Comment by inelgnu** [comment]
@samlesu as discussed I've kept conflict error on tuple creation.

**Review by samlesu — APPROVED** [review]
Thanks!

**Review by thibaultrobert — APPROVED** [review]

**Pull request merged**
