### PR TITLE
Remove obsolete "Model" field from outputTesttuple/outputBoardTuple

### PR DESCRIPTION
**Pull request by AurelienGasser**
This is a follow-up to https://github.com/SubstraFoundation/substra-chaincode/pull/21/files

Remove the now obsolete field `Model` from `outputTesttuple` and `outputBoardTuple`.

### CODE REVIEW

**Review by Kelvin-M — DISMISSED** [review]

**Review by thibaultrobert — APPROVED** [review]
As far as I understand it, this good to merge but @inalgnu wanted to be careful about it. @jmorel and @Kelvin-M, you are still ok with removing the `model` field?

**Comment by Kelvin-M** [comment]
I'm ok as the field is useless now !

**Comment by samlesu** [comment]
LGTM

**Comment by jmorel** [comment]
I'm all for it as well!

**Pull request merged**
